<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\CountrySubdivision;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'flag' => 'af', 'territories' => [
                ['name' => 'Badakhshan'],
                ['name' => 'Badghis'],
                ['name' => 'Baghlan'],
                ['name' => 'Balkh'],
                ['name' => 'Bamyan'],
                ['name' => 'Daykundi'],
                ['name' => 'Farah'],
                ['name' => 'Faryab'],
                ['name' => 'Ghazni'],
                ['name' => 'Ghowr'],
                ['name' => 'Herat'],
                ['name' => 'Helmand'],
                ['name' => 'Jowzjan'],
                ['name' => 'Kabul'],
                ['name' => 'Kandahar'],
                ['name' => 'Kapisa'],
                ['name' => 'Khost'],
                ['name' => 'Kunar'],
                ['name' => 'Kunduz'],
                ['name' => 'Laghman'],
                ['name' => 'Logar'],
                ['name' => 'Nangarhar'],
                ['name' => 'Nimruz'],
                ['name' => 'Nuristan'],
                ['name' => 'Paktia'],
                ['name' => 'Paktya'],
                ['name' => 'Parwan'],
                ['name' => 'Samangan'],
                ['name' => 'Sar-e Pol'],
                ['name' => 'Takhar'],
                ['name' => 'Uruzgan'],
                ['name' => 'Wardak'],
                ['name' => 'Zabul'],
            ]],
            ['name' => 'Albania', 'flag' => 'al', 'territories' => [
                ['name' => 'Berat'],
                ['name' => 'Durres'],
                ['name' => 'Elbasan'],
                ['name' => 'Fier'],
                ['name' => 'Gjirokaster'],
                ['name' => 'Korce'],
                ['name' => 'Kukes'],
                ['name' => 'Lezhe'],
                ['name' => 'Shkoder'],
                ['name' => 'Tirane'],
                ['name' => 'Vlore'],
            ]],
            ['name' => 'Algeria', 'flag' => 'dz'],
            ['name' => 'Andorra', 'flag' => 'ad'],
            ['name' => 'Angola', 'flag' => 'ao'],
            ['name' => 'Antigua and Barbuda', 'flag' => 'ag'],
            ['name' => 'Argentina', 'flag' => 'ar'],
            ['name' => 'Armenia', 'flag' => 'am'],
            ['name' => 'Australia', 'flag' => 'au'],
            ['name' => 'Austria', 'flag' => 'at'],
            ['name' => 'Azerbaijan', 'flag' => 'az'],
            ['name' => 'Bahamas', 'flag' => 'bs'],
            ['name' => 'Bahrain', 'flag' => 'bh'],
            ['name' => 'Bangladesh', 'flag' => 'bd'],
            ['name' => 'Barbados', 'flag' => 'bb'],
            ['name' => 'Belarus', 'flag' => 'by'],
            ['name' => 'Belgium', 'flag' => 'be'],
            ['name' => 'Belize', 'flag' => 'bz'],
            ['name' => 'Benin', 'flag' => 'bj'],
            ['name' => 'Bhutan', 'flag' => 'bt'],
            ['name' => 'Bolivia (Plurinational State of)', 'flag' => 'bo'],
            ['name' => 'Bosnia and Herzegovina', 'flag' => 'ba'],
            ['name' => 'Botswana', 'flag' => 'bw'],
            ['name' => 'Brazil', 'flag' => 'br'],
            ['name' => 'Brunei Darussalam', 'flag' => 'bn'],
            ['name' => 'Bulgaria', 'flag' => 'bg'],
            ['name' => 'Burkina Faso', 'flag' => 'bf'],
            ['name' => 'Burundi', 'flag' => 'bi'],
            ['name' => 'Cabo Verde', 'flag' => 'cv'],
            ['name' => 'Cambodia', 'flag' => 'kh'],
            ['name' => 'Cameroon', 'flag' => 'cm'],
            ['name' => 'Canada', 'flag' => 'ca', 'territories' => [
                ['name' => 'Alberta'],
                ['name' => 'British Columbia'],
                ['name' => 'Manitoba'],
                ['name' => 'New Brunswick'],
                ['name' => 'Newfoundland and Labrador'],
                ['name' => 'Nova Scotia'],
                ['name' => 'Ontario'],
                ['name' => 'Prince Edward Island'],
                ['name' => 'Quebec'],
                ['name' => 'Saskatchewan'],
                ['name' => 'Northwest Territories'],
                ['name' => 'Nunavut'],
                ['name' => 'Yukon'],
            ]],
            ['name' => 'Central African Republic', 'flag' => 'cf'],
            ['name' => 'Chad', 'flag' => 'td'],
            ['name' => 'Chile', 'flag' => 'cl'],
            ['name' => 'China', 'flag' => 'cn'],
            ['name' => 'Colombia', 'flag' => 'co'],
            ['name' => 'Comoros', 'flag' => 'km'],
            ['name' => 'Congo', 'flag' => 'cg'],
            ['name' => 'Congo (Democratic Republic of the)', 'flag' => 'cd'],
            ['name' => 'Costa Rica', 'flag' => 'cr'],
            ['name' => 'Croatia', 'flag' => 'hr'],
            ['name' => 'Cuba', 'flag' => 'cu'],
            ['name' => 'Cyprus', 'flag' => 'cy'],
            ['name' => 'Czech Republic', 'flag' => 'cz'],
            ['name' => 'Denmark', 'flag' => 'dk'],
            ['name' => 'Djibouti', 'flag' => 'dj'],
            ['name' => 'Dominica', 'flag' => 'dm'],
            ['name' => 'Dominican Republic', 'flag' => 'do'],
            ['name' => 'Ecuador', 'flag' => 'ec'],
            ['name' => 'Egypt', 'flag' => 'eg'],
            ['name' => 'El Salvador', 'flag' => 'sv'],
            ['name' => 'Equatorial Guinea', 'flag' => 'gq'],
            ['name' => 'Eritrea', 'flag' => 'er'],
            ['name' => 'Estonia', 'flag' => 'ee'],
            ['name' => 'Eswatini', 'flag' => 'sz'],
            ['name' => 'Ethiopia', 'flag' => 'et'],
            ['name' => 'Fiji', 'flag' => 'fj'],
            ['name' => 'Finland', 'flag' => 'fi'],
            ['name' => 'France', 'flag' => 'fr'],
            ['name' => 'Gabon', 'flag' => 'ga'],
            ['name' => 'Gambia', 'flag' => 'gm'],
            ['name' => 'Georgia', 'flag' => 'ge'],
            ['name' => 'Germany', 'flag' => 'de'],
            ['name' => 'Ghana', 'flag' => 'gh'],
            ['name' => 'Greece', 'flag' => 'gr'],
            ['name' => 'Grenada', 'flag' => 'gd'],
            ['name' => 'Guatemala', 'flag' => 'gt'],
            ['name' => 'Guinea', 'flag' => 'gn'],
            ['name' => 'Guinea-Bissau', 'flag' => 'gw'],
            ['name' => 'Guyana', 'flag' => 'gy'],
            ['name' => 'Haiti', 'flag' => 'ht'],
            ['name' => 'Honduras', 'flag' => 'hn'],
            ['name' => 'Hungary', 'flag' => 'hu'],
            ['name' => 'Iceland', 'flag' => 'is'],
            ['name' => 'India', 'flag' => 'in'],
            ['name' => 'Indonesia', 'flag' => 'id'],
            ['name' => 'Iran (Islamic Republic of)', 'flag' => 'ir'],
            ['name' => 'Iraq', 'flag' => 'iq'],
            ['name' => 'Ireland', 'flag' => 'ie'],
            ['name' => 'Israel', 'flag' => 'il'],
            ['name' => 'Italy', 'flag' => 'it'],
            ['name' => 'Jamaica', 'flag' => 'jm'],
            ['name' => 'Japan', 'flag' => 'jp'],
            ['name' => 'Jordan', 'flag' => 'jo'],
            ['name' => 'Kazakhstan', 'flag' => 'kz'],
            ['name' => 'Kenya', 'flag' => 'ke'],
            ['name' => 'Kiribati', 'flag' => 'ki'],
            ['name' => 'Kuwait', 'flag' => 'kw'],
            ['name' => 'Kyrgyzstan', 'flag' => 'kg'],
            ['name' => 'Lao People\'s Democratic Republic', 'flag' => 'la'],
            ['name' => 'Latvia', 'flag' => 'lv'],
            ['name' => 'Lebanon', 'flag' => 'lb'],
            ['name' => 'Lesotho', 'flag' => 'ls'],
            ['name' => 'Liberia', 'flag' => 'lr'],
            ['name' => 'Libya', 'flag' => 'ly'],
            ['name' => 'Liechtenstein', 'flag' => 'li'],
            ['name' => 'Lithuania', 'flag' => 'lt'],
            ['name' => 'Luxembourg', 'flag' => 'lu'],
            ['name' => 'Madagascar', 'flag' => 'mg'],
            ['name' => 'Malawi', 'flag' => 'mw'],
            ['name' => 'Malaysia', 'flag' => 'my'],
            ['name' => 'Maldives', 'flag' => 'mv'],
            ['name' => 'Mali', 'flag' => 'ml'],
            ['name' => 'Malta', 'flag' => 'mt'],
            ['name' => 'Marshall Islands', 'flag' => 'mh'],
            ['name' => 'Mauritania', 'flag' => 'mr'],
            ['name' => 'Mauritius', 'flag' => 'mu'],
            ['name' => 'Mexico', 'flag' => 'mx'],
            ['name' => 'Micronesia (Federated States of)', 'flag' => 'fm'],
            ['name' => 'Moldova (Republic of)', 'flag' => 'md'],
            ['name' => 'Monaco', 'flag' => 'mc'],
            ['name' => 'Mongolia', 'flag' => 'mn'],
            ['name' => 'Montenegro', 'flag' => 'me'],
            ['name' => 'Morocco', 'flag' => 'ma'],
            ['name' => 'Mozambique', 'flag' => 'mz'],
            ['name' => 'Myanmar', 'flag' => 'mm'],
            ['name' => 'Namibia', 'flag' => 'na'],
            ['name' => 'Nauru', 'flag' => 'nr'],
            ['name' => 'Nepal', 'flag' => 'np'],
            ['name' => 'Netherlands', 'flag' => 'nl'],
            ['name' => 'New Zealand', 'flag' => 'nz'],
            ['name' => 'Nicaragua', 'flag' => 'ni'],
            ['name' => 'Niger', 'flag' => 'ne'],
            ['name' => 'Nigeria', 'flag' => 'ng'],
            ['name' => 'North Macedonia', 'flag' => 'mk'],
            ['name' => 'Norway', 'flag' => 'no'],
            ['name' => 'Oman', 'flag' => 'om'],
            ['name' => 'Pakistan', 'flag' => 'pk'],
            ['name' => 'Palau', 'flag' => 'pw'],
            ['name' => 'Panama', 'flag' => 'pa'],
            ['name' => 'Papua New Guinea', 'flag' => 'pg'],
            ['name' => 'Paraguay', 'flag' => 'py'],
            ['name' => 'Peru', 'flag' => 'pe'],
            ['name' => 'Philippines', 'flag' => 'ph'],
            ['name' => 'Poland', 'flag' => 'pl'],
            ['name' => 'Portugal', 'flag' => 'pt'],
            ['name' => 'Qatar', 'flag' => 'qa'],
            ['name' => 'Republic of Korea', 'flag' => 'kr'],
            ['name' => 'Romania', 'flag' => 'ro'],
            ['name' => 'Russian Federation', 'flag' => 'ru'],
            ['name' => 'Rwanda', 'flag' => 'rw'],
            ['name' => 'Saint Kitts and Nevis', 'flag' => 'kn'],
            ['name' => 'Saint Lucia', 'flag' => 'lc'],
            ['name' => 'Saint Vincent and the Grenadines', 'flag' => 'vc'],
            ['name' => 'Samoa', 'flag' => 'ws'],
            ['name' => 'San Marino', 'flag' => 'sm'],
            ['name' => 'Sao Tome and Principe', 'flag' => 'st'],
            ['name' => 'Saudi Arabia', 'flag' => 'sa'],
            ['name' => 'Senegal', 'flag' => 'sn'],
            ['name' => 'Serbia', 'flag' => 'rs'],
            ['name' => 'Seychelles', 'flag' => 'sc'],
            ['name' => 'Sierra Leone', 'flag' => 'sl'],
            ['name' => 'Singapore', 'flag' => 'sg'],
            ['name' => 'Slovakia', 'flag' => 'sk'],
            ['name' => 'Slovenia', 'flag' => 'si'],
            ['name' => 'Solomon Islands', 'flag' => 'sb'],
            ['name' => 'Somalia', 'flag' => 'so'],
            ['name' => 'South Africa', 'flag' => 'za'],
            ['name' => 'South Sudan', 'flag' => 'ss'],
            ['name' => 'Spain', 'flag' => 'es'],
            ['name' => 'Sri Lanka', 'flag' => 'lk'],
            ['name' => 'Sudan', 'flag' => 'sd'],
            ['name' => 'Suriname', 'flag' => 'sr'],
            ['name' => 'Sweden', 'flag' => 'se'],
            ['name' => 'Switzerland', 'flag' => 'ch'],
            ['name' => 'Syrian Arab Republic', 'flag' => 'sy'],
            ['name' => 'Tajikistan', 'flag' => 'tj'],
            ['name' => 'Thailand', 'flag' => 'th'],
            ['name' => 'Timor-Leste', 'flag' => 'tl'],
            ['name' => 'Togo', 'flag' => 'tg'],
            ['name' => 'Tonga', 'flag' => 'to'],
            ['name' => 'Trinidad and Tobago', 'flag' => 'tt'],
            ['name' => 'Tunisia', 'flag' => 'tn'],
            ['name' => 'Turkey', 'flag' => 'tr'],
            ['name' => 'Turkmenistan', 'flag' => 'tm'],
            ['name' => 'Tuvalu', 'flag' => 'tv'],
            ['name' => 'Uganda', 'flag' => 'ug'],
            ['name' => 'Ukraine', 'flag' => 'ua'],
            ['name' => 'United Arab Emirates', 'flag' => 'ae'],
            ['name' => 'United Kingdom', 'flag' => 'gb'],
            ['name' => 'United States of America', 'flag' => 'us', 'territories' => [
                ['name' => 'Alabama'],
                ['name' => 'Alaska'],
                ['name' => 'Arizona'],
                ['name' => 'Arkansas'],
                ['name' => 'California'],
                ['name' => 'Colorado'],
                ['name' => 'Connecticut'],
                ['name' => 'Delaware'],
                ['name' => 'Florida'],
                ['name' => 'Georgia'],
                ['name' => 'Hawaii'],
                ['name' => 'Idaho'],
                ['name' => 'Illinois'],
                ['name' => 'Indiana'],
                ['name' => 'Iowa'],
                ['name' => 'Kansas'],
                ['name' => 'Kentucky'],
                ['name' => 'Louisiana'],
                ['name' => 'Maine'],
                ['name' => 'Maryland'],
                ['name' => 'Massachusetts'],
                ['name' => 'Michigan'],
                ['name' => 'Minnesota'],
                ['name' => 'Mississippi'],
                ['name' => 'Missouri'],
                ['name' => 'Montana'],
                ['name' => 'Nebraska'],
                ['name' => 'Nevada'],
                ['name' => 'New Hampshire'],
                ['name' => 'New Jersey'],
                ['name' => 'New Mexico'],
                ['name' => 'New York'],
                ['name' => 'North Carolina'],
                ['name' => 'North Dakota'],
                ['name' => 'Ohio'],
                ['name' => 'Oklahoma'],
                ['name' => 'Oregon'],
                ['name' => 'Pennsylvania'],
                ['name' => 'Rhode Island'],
                ['name' => 'South Carolina'],
                ['name' => 'South Dakota'],
                ['name' => 'Tennessee'],
                ['name' => 'Texas'],
                ['name' => 'Utah'],
                ['name' => 'Vermont'],
                ['name' => 'Virginia'],
                ['name' => 'Washington'],
                ['name' => 'West Virginia'],
                ['name' => 'Wisconsin'],
                ['name' => 'Wyoming'],
                ['name' => 'American Samoa'],
                ['name' => 'Guam'],
                ['name' => 'Northern Mariana Islands'],
                ['name' => 'Puerto Rico'],
                ['name' => 'United States Minor Outlying Islands'],
                ['name' => 'United States Virgin Islands'],
            ]],
            ['name' => 'Uruguay', 'flag' => 'uy'],
            ['name' => 'Uzbekistan', 'flag' => 'uz'],
            ['name' => 'Vanuatu', 'flag' => 'vu'],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'flag' => 've'],
            ['name' => 'Viet Nam', 'flag' => 'vn'],
            ['name' => 'Yemen', 'flag' => 'ye'],
            ['name' => 'Zambia', 'flag' => 'zm'],
            ['name' => 'Zimbabwe', 'flag' => 'zw'],
        ];

        $flagFileExtension = '.svg';

        foreach ($countries as $key => $country) {
            $countries[$key]['flag'] = $country['flag'].$flagFileExtension;
            $countries[$key]['code'] = strtoupper($country['flag']);

            $id = Country::insertGetId([
                'name' => $countries[$key]['name'],
                'code' => $countries[$key]['code'],
                'flag' => $countries[$key]['flag'],
            ]);

            foreach ($country['territories'] ?? [] as $territory) {
                $territory['country_id'] = $id;
                CountrySubdivision::insert($territory);
            }
        }
    }
}
